using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.InputSystem;

/// <summary>
/// ЧУЗЙРЬОю ПђСїРг ЛѓХТ enum
/// </summary>
enum MoveState
{   // ПђСїРг ЛѓХТ
    Idle = 0,
    Walk,
    Sprint,
}

enum WeaponState
{
    Sword = 0,
    Bow
}

// Player-Weapon ХзНКЦЎ РЮЧВПы НКХЉИГЦЎ
public class Test_Player : MonoBehaviour
{
    // ЙіЦАРИЗЮ ЙЋБт БГУМ УпАЁЧЯАэ ША РЮЧВ НЧЧш

    MoveState moveState;        // ПђСїРг ЛѓХТ Enum
    [SerializeField] WeaponState weaponState;    // ЧіРч АЁСіАэ РжДТ ЙЋБт Enum

    WeaponState CurrentWeaponState
    {
        get => weaponState;
        set
        {
            weaponState = value;
            switch (weaponState)
            {
                case WeaponState.Sword:
                    inputActions.Sword.Enable();
                    inputActions.Bow.Disable();
                    break;
                case WeaponState.Bow:
                    inputActions.Sword.Disable();
                    inputActions.Bow.Enable();
                    break;
            }
        }
    }

    /// <summary>
    /// ЧУЗЙРЬОю ПђСїРг ЛѓХТПЁ ЕћИЅ КЏМіАЊ КЏАц ЧСЗЮЦлЦМ
    /// </summary>
    MoveState PlayerMoveState
    {
        get => moveState;
        set
        {
            moveState = value;
            switch(moveState)
            {
                case MoveState.Idle:
                    animMoveSpeed = 0f;
                    break;
                case MoveState.Walk:
                    animMoveSpeed = 0.5f;
                    break;
                case MoveState.Sprint:
                    animMoveSpeed = 1f;
                    break;
            }
        }
    }

    // Components
    PlayerInputActions inputActions;
    CharacterController controller;
    Animator animator;
    Sword sword;

    // Values
    Vector3 inputDirection = Vector3.zero;                          // РдЗТ ЙоДТ ЙцЧт КЄХЭ
    public float moveSpeed = 3f;                                    // НЧСІ ЧУЗЙРЬОю РЬЕПМгЕЕ
    Vector3 smoothInputVelocity = Vector3.zero;                     // SmoothDampПы ЧіРч VelocityАЊ
    [Tooltip("ЧУЗЙРЬОюАЁ УжАэ МгЕЕПЁ ЕЕДоЧв МгЕЕ АЊ( АЊРЬ ГЗРЛ МіЗЯ Дѕ ЛЁИЎ ЕЕДоЧд , Default : 0.2)")]
    [SerializeField] float smoothInputSpeed = .2f;                  // SmoothDampАЁ ЕЕДоЧв АЊ ( АЊРЬ РлРЛ МіЗЯ Дѕ ЛЁИЎ ЕЕДоЧд )
    float animMoveSpeed = 0f;                                       // ОжДЯИоРЬМЧ ЦФЖѓЙЬХЭ РќДоПы ЧдМі

    //rotate
    Vector3 lookVector = Vector3.zero;                              // ИЖПьНК РЮЧВАЊ
    public GameObject followCam;                                    // CinemachineРЬ ЙйЖѓКИДТ ПРКъСЇЦЎ
    Quaternion camY;                                                // ИоРЮ ФЋИоЖѓ YАЊ
    public float rotatePower = 5f;                                  // ШИРќАЊ

    [SerializeField] Vector3 currentMoveVector = Vector3.zero;
    Quaternion targetRotation = Quaternion.identity;                // ШИРќЧв ИёЧЅ ШИРќАЊ
    //public float turnspeed = 10.0f;                                 // ШИРќ МгЕЕ

    [SerializeField]bool isAttack = false;                          // АјАнЧпДТСі ШЎРЮ
   
    // Hashes
    readonly int SpeedToHash = Animator.StringToHash("Speed");              // РЬЕППы ЦФЖѓЙЬХЭ
    readonly int AttackToHash = Animator.StringToHash("Attack");            // АјАнПы ЦФЖѓЙЬХЭ
    readonly int IsEquipToHash = Animator.StringToHash("IsEquip");          // ЙЋБтРхКёТјПы ПЉКЮ 
    readonly int IsWeaponBowToHash = Animator.StringToHash("IsWeaponBow");  // ЧіРч ЙЋБтАЁ ШАРЮСі УМХЉ ( true : ША )

    // delegate
    public Action OnAttackEnd;  // ЧУЗЙРЬОю АјАнРЬ СОЗсЕЧИщ НЧЧрЕЧДТ ЕЈИЎАдРЬЦЎ

    void Awake()
    {
        inputActions = new PlayerInputActions();
        controller = GetComponent<CharacterController>();
        animator = GetComponent<Animator>();
        sword = GetComponentInChildren<Sword>();

        PlayerMoveState = MoveState.Idle;
        CurrentWeaponState = WeaponState.Sword;

        OnAttackEnd += DisableIsAttack;
    }

    void OnEnable()
    {
        inputActions.Main.Enable();
        inputActions.Main.Move.performed += OnMoveInput;
        inputActions.Main.Move.canceled += OnMoveInput;
        inputActions.Main.Sprint.performed += OnSpritInput;
        inputActions.Main.Sprint.canceled += OnSpritInput;

        inputActions.Main.Look.performed += OnLookInput;
        inputActions.Main.Look.canceled += OnLookInput;

        inputActions.Main.SwitchWeapon.performed += OnWeaponSwitchInput;

        inputActions.Sword.Attack.performed += OnAttackInput;
        inputActions.Sword.Attack.canceled += OnAttackInput;

        inputActions.Bow.Shot.performed += OnBowShotInput;
        inputActions.Bow.AimDown.performed += OnAimDownInput;
    }

    void OnDisable()
    {
        inputActions.Bow.AimDown.performed -= OnAimDownInput;
        inputActions.Bow.Shot.performed -= OnBowShotInput;

        inputActions.Sword.Attack.canceled -= OnAttackInput;
        inputActions.Sword.Attack.performed -= OnAttackInput;

        inputActions.Main.Look.canceled -= OnLookInput;
        inputActions.Main.Look.performed -= OnLookInput;

        inputActions.Main.Sprint.canceled -= OnSpritInput;
        inputActions.Main.Sprint.performed -= OnSpritInput;
        inputActions.Main.Move.canceled -= OnMoveInput;
        inputActions.Main.Move.performed -= OnMoveInput;

        inputActions.Main.Disable();      
        inputActions.Sword.Disable();      
        inputActions.Bow.Disable();      
    }

    void Update()
    {
        LookRotation();

        if (!isAttack)
            OnMove();
    }

    private void OnAttackInput(InputAction.CallbackContext context) // БйСЂЙЋБт
    {
        if (weaponState == WeaponState.Bow)
            return;

        if (context.performed && !isAttack)
        {
            isAttack = true;            // АјАн ШЎРЮ 
            animator.SetTrigger(AttackToHash);
            animator.SetBool(IsEquipToHash, true);
        }
    }

    private void OnMoveInput(InputAction.CallbackContext context)
    {
        Vector2 inputVector = context.ReadValue<Vector2>();

        inputDirection.x = inputVector.x;
        inputDirection.z = inputVector.y;

        if (context.performed)
        {
            camY = Quaternion.Euler(0, Camera.main.transform.localEulerAngles.y, 0);         // ФЋИоЖѓ YАЊ
            inputDirection = camY * inputDirection;                                          // ФЋИоЖѓ БтСи ШИРќАЊ
            targetRotation = Quaternion.LookRotation(inputDirection * Time.deltaTime);       // ШИРќЧв ЙцЧтАЊ
            PlayerMoveState = MoveState.Walk;
        }
        else
        {
            PlayerMoveState = MoveState.Idle;
        }
    }

    private void OnSpritInput(InputAction.CallbackContext context)
    {
        if (context.performed && PlayerMoveState == MoveState.Walk)
        {
            PlayerMoveState = MoveState.Sprint;
        }
    }

    public bool isLook = false;
    private void OnLookInput(InputAction.CallbackContext context)
    {
        if(context.performed)
        {
            isLook = true;
            lookVector = context.ReadValue<Vector2>();
        }
        if(!context.performed)
        {
            isLook = false;
        }
    }

    private void OnWeaponSwitchInput(InputAction.CallbackContext context)
    {
        if (context.performed)
        {
            switch (weaponState)
            {
                case WeaponState.Sword:
                    CurrentWeaponState = WeaponState.Bow;
                    animator.SetBool(IsWeaponBowToHash, true);
                    break;
                case WeaponState.Bow:
                    CurrentWeaponState = WeaponState.Sword;
                    animator.SetBool(IsWeaponBowToHash, false);
                    break;
            }
        }
    }

    private void OnAimDownInput(InputAction.CallbackContext context)
    {
        if (context.performed && !animator.GetBool("AimDown"))
        {
            animator.SetTrigger("RangeAttack");
            animator.SetBool("AimDown", true);
            Debug.Log("Ш­Ль СЖСи");
        }
    }

    private void OnBowShotInput(InputAction.CallbackContext context)
    {
        if (context.performed && animator.GetBool("AimDown"))
        {
            animator.SetBool("AimDown", false);
            Debug.Log("Ш­Ль ЙпЛч");
        }
    }

    /// <summary>
    /// ПђСїРЯ ЖЇ НЧЧрЧЯДТ ЧдМі
    /// </summary>
    void OnMove()
    {
        // turn
        transform.rotation = Quaternion.Slerp(transform.rotation, targetRotation, Time.deltaTime * 10f);     // ШИРќ

        currentMoveVector = Vector3.SmoothDamp(currentMoveVector, inputDirection, ref smoothInputVelocity, smoothInputSpeed);   // ПђСїРг КИСЄ\

        controller.Move(Time.fixedDeltaTime * currentMoveVector * moveSpeed);   // ЧУЗЙРЬОю ПђСїРг

        animator.SetFloat(SpeedToHash, animMoveSpeed);  // ОжДЯИоРЬМЧ ЦФЖѓЙЬХЭ КЏАц
    }

    void LookRotation()
    {
        if (!isLook)
            return;

        #region Rotation

        followCam.transform.localRotation *= Quaternion.AngleAxis(lookVector.x * rotatePower, Vector3.up);
        followCam.transform.localRotation *= Quaternion.AngleAxis(-lookVector.y * rotatePower, Vector3.right);

        var angles = followCam.transform.localEulerAngles;
        angles.z = 0;

        var angle = followCam.transform.localEulerAngles.x;

        if (angle > 180 && angle < 340)
        {
            angles.x = 340;
        }
        else if (angle < 180 && angle > 40)
        {
            angles.x = 40;
        }

        followCam.transform.localEulerAngles = angles;

        //transform.rotation = Quaternion.Euler(0, followCam.transform.rotation.eulerAngles.y + targetRotation, 0);

        followCam.transform.localEulerAngles = new Vector3(angles.x, angles.y, 0);

        #endregion

    }

    void DisableIsAttack()
    {
        isAttack = false;
    }

    void WeaponColliderEnable()
    {
        sword.MeleeWeaponColliderEnable();
    }

    void WeaponColliderDisable()
    {
        sword.MeleeWeaponColliderDisable();
    }
}